name: server CI/CD pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x, 16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version}}
        uses: actions/checkout@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install --prefix server
      - run: npm run test --prefix server